### ISSUE TITLE
Question: How to config the js API URL? 

### ISSUE THREAD

**Issue by zj8487** [nicksenger/react-arcgis#1]
Hi, Nick Senger:

Thank your work so much, and i like this react component very much.

But i notice that there is no flag to control which version or url address of the arcgis js API server.

Is it possible to config for this?

thanks a lot!

**Comment by jgravois** [comment]
it looks to me like [`this.props.scriptUri`](https://github.com/nicksenger/react-arcgis/blob/ba1d5d3fe4ebe55486fd9e02757db6778dda6b1b/src/ts/components/ArcBase.tsx#L131) is the constructor option you'd use to target a specific version/location to fetch the API. have you already tried setting that?

https://github.com/nicksenger/esri-promise#use

**Comment by zj8487** [comment]
@jgravois  thank you very much.  

The [this.props.scriptUri](https://github.com/nicksenger/react-arcgis/blob/ba1d5d3fe4ebe55486fd9e02757db6778dda6b1b/src/ts/components/ArcBase.tsx#L131) is used for the [relative module path](https://github.com/nicksenger/react-arcgis/blob/2d96741a909149cb7d9e558fff1a059fd6a6b56e/src/ts/components/symbols/SymbolComposites.tsx#L14).

and this component may can not set the [url address of the arcgis js API server].

Is there a good suggestion for esri usage in react that Sceneview(3d) is supported well and lightly (no need to download so much code)?

**Comment by nicksenger** [comment]
@zj8487 

Currently react-arcgis will only work with the 4.x API, and loads version 4.3 by default. If you'd like to use an earlier version, you can pre-load one using esriBootstrap before mounting the first react-arcgis component.

`
import { esriBootstrap } from 'esri-promise';

esriBootstrap(`${api_url}`).then(() => {
  // Mount the react-arcgis component
})`

Keep in mind that if you mount any component from react-arcgis prior to calling esriBootstrap with your intended API version, it will have already loaded version 4.3 of the API, so you have to do esriBootstrap before any react-arcgis components are mounted (they load the API scripts if necessary in the componentWillMount handler)

**Comment by nicksenger** [comment]
@jgravois 

Just to clarify, changing the value of `this.props.scriptUri` in `ArcBase` won't give the desired results here. That value is relative to what the js API sets the `esri` path to for the dojo loader, and is just changed depending on whether a map or scene is being rendered.

Setting the desired api version at the entrypoint of your application with `esriBootstrap` will ensure that all widgets, symbols, layers, etc are being pulled from the right place.
