### ISSUE TITLE
Does this package support all the ESRI JS API functionalities?

### ISSUE THREAD

**Issue by lwconquer** [nicksenger/react-arcgis#17]
This package looks prettey good! But I just want to make sure if it supports all the functionalities from ESRI's JS API, such as QueryTask, Print widget, Legend widget, Popup widget, etc.

Thanks,
Wei

**Comment by nicksenger** [comment]
Hi Wei,

I havent specifically added support for the QueryTask, and am currently
working on a better implementation for popups. All of the default widgets
from the API are supported however.

If you need access to some of the more fine-grained API features, you may
want to also look into esri-promise, which is a thin wrapper for the api
that makes it easier to use with react (commonjs) style applications.
React-arcgis is built off of this lower level wrapper.

Best,
Nick

**Comment by nicksenger** [comment]
Hi Wei,

I havent specifically added support for the QueryTask, and am currently working on a better implementation for popups. All of the default widgets from the API are supported however, and you can use [esri-promise](https://www.npmjs.com/package/esri-promise) to access API features that are not yet part of the library. It is included as part of react-arcgis.

Nick
