### ISSUE TITLE
Painting graphic in a map does not work

### ISSUE THREAD

**Issue by adrianortuzar** [nicksenger/react-arcgis#2]
Hi, I am trying to paint a simple circle in a map. I can see the circle painted before the map load. Once is loaded the circle is not there. Looks like is behind the map.

Thank you for the library.

```
<Map
    style={{ width: '100%', height: '500px' }}
    mapProperties={{
        basemap: "topo-vector",
    }}
    viewProperties={{
        center: [4.305098, 51.895311],
        zoom: 10
    }}
>
    <Graphic>
        <Geometry.Point
            geometryProperties={{
                latitude: 51.895311,
                longitude: 4.305098
            }}
        />
        <Symbols.SimpleMarkerSymbol
            symbolProperties={{
                color: [226, 119, 40],
                outline: {
                    color: [255, 255, 255],
                    width: 2
                }
            }}
        />
    </Graphic>
</Map>
```

**Comment by nicksenger** [comment]
@adrianortuzar 

Thanks for letting me know! I will take a look at this.

**Comment by nicksenger** [comment]
Try adding the following inside the `<head>` of your html file and let me know if that fixes the issue:

`<link rel="stylesheet" href="https://js.arcgis.com/4.3/esri/css/main.css">`

React-arcgis wont load the stylesheet for the API, so you have to include this link in your html to get Esri's styles.

**Comment by nicksenger** [comment]
I think that was the issue, so am going to close this for now. 

Just let me know if you're still having problems!
