### ISSUE TITLE
Map rendering a little strange

### ISSUE THREAD

**Issue by CraigglesO** [nicksenger/react-arcgis#26]
Widgets won't load for me unfortunately. And this is what `<Map />` Looks like:

<img width="1280" alt="screenshot 2017-09-08 22 50 59" src="https://user-images.githubusercontent.com/5249140/30237127-91097a7a-94e8-11e7-8cd8-944cecea3323.png">

any advice?

**Comment by nicksenger** [comment]
@CraigglesO you still need to load Esri's CSS file for the JS API somewhere in your html file(s):

`<link rel="stylesheet" href="https://js.arcgis.com/4.4/esri/css/main.css">`

**Comment by CraigglesO** [comment]
Hey, sorry had to call quits on this project for a while. The issue I think was that I was using electron rather then a browser. As long as I work on these maps in the browser, no problems. Thanks for your hard work.

**Comment by nicksenger** [comment]
No worries, yeah I haven't tried using this in the context of an electron app so I'm not sure if that would work or not. I''ll make a note of looking into it when I have the chance!
