### ISSUE TITLE
Displaying text graphics

### ISSUE THREAD

**Issue by Rumptadump** [nicksenger/react-arcgis#28]
We are using react-arcgis to display maps for our application and I'd like to display text on the map. I'm not real familiar with creating esri maps but it seems like this would be done using a TextSymbol inside Graphic. However, I'm not seeing TextSymbol as an option of the Symbols component. Is there another way to display text on a map with react-arcgis or is TextSymbol something that could be added to the package. Thanks for any direction you might provide.

**Comment by nicksenger** [comment]
@Rumptadump there is nothing specifically implemented in react-arcgis to accomplish this, however the ArcGIS JS API itself provides this functionality. You will need to interact with the map/view instance directly to use the underlying ArcGIS JS API. You can get a reference to the instances from an `onLoad` handler defined on the map/scene.

For example:

```js
render() {
  return (
    <Map onLoad={this.handleMapLoad} />
  );
}

handleMapLoad(map, view) {
  // do something with the map or view instances like add text
}
```

For more info see the [ArcGIS API for JavaScript documentation](https://developers.arcgis.com/javascript/latest/api-reference/index.html)

[This link specifically will probably be useful](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-TextSymbol.html)
