### ISSUE TITLE
The ArcGIS API failed to load.

### ISSUE THREAD

**Issue by maka-io** [nicksenger/react-arcgis#29]
Using Meteor 1.6, React, and GraphQL with this simple example:

``` js
import { graphql, compose } from 'react-apollo';
import gql from 'graphql-tag';

import React, { Component } from 'react';
import { Map } from 'react-arcgis';

class HomeComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {};
    }


    render() {
        return (
            <Map style={{ height: '95vh', width: '95vw' }} />
        );
    }
}

const geoJSON = gql`
    {
        features
    }
`;
const Home = compose(
    graphql(geoJSON),
)(HomeComponent);

export { Home, HomeComponent };

**Comment by maka-io** [comment]
Here is the solution if you're using Meteor 1.6 and React:

``` sh
    $ meteor npm install --save esri-loader esri-loader-react react-arcgis
```

Then, in your component adapted from this solution: [esri-loader-react](https://github.com/davetimmins/esri-loader-react)

``` js
import React, { Component } from 'react';
import EsriLoader from 'esri-loader-react';
import { Map } from 'react-arcgis';

class Home extends Component {

    constructor(props) {
        super(props);
        this.state = {
            loaded: false
        };
    }

    render() {
      const options = {
        url: 'https://js.arcgis.com/4.3/'
      };

      return (
        <div>
          <EsriLoader options={options} ready={this.onEsriApiLoaded}/>
          { this.state.loaded ?
              <Map style={{ height: '95vh', width: '95vw'}}/> : null }
        </div>
        );
    }

    onEsriApiLoaded = (error) => {
        if (!error) {
          this.setState({loaded: true});
        }
      }
}
```

**Comment by nicksenger** [comment]
@maka-io that's interesting! The implementation for `esri-loader` and `esri-promise` is very similar so I'm curious what is causing this. Will try to reproduce and fix for the next version.

If you have the chance, you might try bootstrapping the ArcGIS JS API prior to instantiating the `<Map />` like this:

```js
import React, { Component } from 'react';
import { esriBootstrap } from 'esri-promise';
import { Map } from 'react-arcgis';

class Home extends Component {
    
    constructor(props) {
        super(props);
        this.state = {
            loaded: false
        };
    }

    render() {
        const options = {
        url: 'https://js.arcgis.com/4.3/'
        };

        return (
        <div>
            { this.state.loaded ? <Map style={{ height: '95vh', width: '95vw'}}/> : null }
        </div>
        );
    }

    componentWillMount() {
        esriBootstrap().then(() => {
            this.setState({ loaded: true });
        });
    }
}
```

`esri-promise` is a dependency of `react-arcgis`, so you will already have it available

**Comment by nicksenger** [comment]
@maka-io 

I think I got to the bottom of this one and wanted to give you a bit of a heads-up. It looks like apollo client (or some associated lib) is already defining `window.require`, so when you load the ArcGIS js api (using either esri-loader or esri-promise) it *will overwrite the existing global require*. This is necessary in order for the js api to function.

I'm not sure what the ramifications of this will be in your app because I'm not that familiar with apollo, but dojo's require is a bit different from requirejs and other libs, so it's something to be aware of.

Unfortunately I don't know of any way to completely encapsulate the js api without severely hampering the user's ability to interact with it..

**Comment by maka-io** [comment]
@nicksenger Wow! That's very interesting, I'll have to keep an eye out for odd behavior and see if I can make a compromise between the Esri and Apollo stacks.

 I appreciate it, thanks!

**Comment by rosemarystanley** [comment]
> @maka-io that's interesting! The implementation for `esri-loader` and `esri-promise` is very similar so I'm curious what is causing this. Will try to reproduce and fix for the next version.
> 
> If you have the chance, you might try bootstrapping the ArcGIS JS API prior to instantiating the `<Map />` like this:
> 
> ```js
> import React, { Component } from 'react';
> import { esriBootstrap } from 'esri-promise';
> import { Map } from 'react-arcgis';
> 
> class Home extends Component {
>     
>     constructor(props) {
>         super(props);
>         this.state = {
>             loaded: false
>         };
>     }
> 
>     render() {
>         return (
>         <div>
>             { this.state.loaded ? <Map style={{ height: '95vh', width: '95vw'}}/> : null }
>         </div>
>         );
>     }
> 
>     componentWillMount() {
>         esriBootstrap().then(() => {
>             this.setState({ loaded: true });
>         });
>     }
> }
> ```
> 
> `esri-promise` is a dependency of `react-arcgis`, so you will already have it available

@nicksenger This was a big help getting my basemap to show... I'm using this inside an Electron react app. 

But in my case, now, the Map component doesn't call the `onLoad` method or really any other state changes. For example, in my instance, I'm sending center and zoom as state to reset the map when I needed. The below code works great in a browser (and `this._onLoad` works as expected) but when inside the electron app, the basemap loads but the rest of the API doesn't. (I get the API failed to load message over top the basemap and the map contains no markers. But I can interact by zooming / moving the map.) There are no additional errors tho either from the console. Is there an additional method I need to call to load the rest of the API?

```
let Points = []

Points = points.map((x, i) => (
    <Marker
        key={i}
        center={center}
        data={x}
        index={i}
        visible={mode === 'map'}
        zoom={zoom} />
))

<Map
    mapProperties={{
        basemap: basemap
    }}
    viewProperties={{
        center: center,
        zoom: zoom
    }}
    onLoad={(map, view) => this._onLoad(map, view)}>
    {Points}
</Map>
```


Also if I insert the latest url `https://js.arcgis.com/4.11/` in the esriBootrap method, I get additional errors from dojo, but I'm not sure if that's relevant. But I'll add it here anyway just in case. Thanks! 

```
esriBootstrap('https://js.arcgis.com/4.11/').then(() => {
    ...
})
```
![Screen Shot 2019-06-10 at 10 00 58 AM](https://user-images.githubusercontent.com/7914791/59200633-af91be00-8b66-11e9-9406-b47c1a4e910e.png)

**Comment by tomwayson** [comment]
> Also if I insert the latest url https://js.arcgis.com/4.11/ in the esriBootrap method, I get additional errors from dojo, but I'm not sure if that's relevant. But I'll add it here anyway just in case. Thanks!

Are you using `nodeIntegration: true`? If so those errors may be related to https://github.com/Esri/esri-loader/issues/147 and you might want to try version 4.7 to see if it gets rid of those errors.

Generally speaking, I'd try and get your Electron app working w/ esri-loader and your own custom map component rather than trying to get react-arcgis working in Electron.

There are plenty of custom map component implementations that you can reference:

https://codesandbox.io/s/8ykw098vw0
https://codesandbox.io/s/qzzwql0yn9
https://github.com/tomwayson/create-arcgis-app/blob/master/src/components/ExtentsMap.js
https://github.com/Esri/esri-loader#react

**Comment by rosemarystanley** [comment]
Thanks @tomwayson I'll give those a try. Appreciate it.
