### ISSUE TITLE
Legend out of a map

### ISSUE THREAD

**Issue by baierjak** [nicksenger/react-arcgis#31]
Hello,

please we would need Legend component from Widgets put out of a WebScene. Is that possible? 
Actually we have reach our goal to create it out of the WebScene container through the 'view' attribute but after its loaded the legend is shown still in the Map.
We really appreciate your work!

Thank you,
Jakub

**Comment by baierjak** [comment]
There is whole code of this component. This solution works but it is very bad to move those element in React. Is there any chance to set an ID of container where will be the Legend created? 

```
import React, { Component } from 'react';
import { WebScene, Widgets } from 'react-arcgis';

const Search = Widgets.Locate;
const Legend = Widgets.Legend;

export default class Map extends Component {
    constructor(props){
        super(props);
        this.state = {
            map: undefined,
            view: undefined,
            position: undefined,
        };
    }

    componentDidMount(){
        console.log('nactena componenta');
    }

    onMapLoad = (map, view) => {
        console.log("nactena mapa");
        this.setState({
            map: map,
            view
        });
    }

    onLegendLoad = () => {
        document.getElementById('legenda').appendChild(document.getElementById('legendaFlexible'));
    }

    render () {
        return (
            <span>
                <WebScene
                    id={this.state}
                    style={{ display: 'block', width: '100%', height: '90vh'}}
                    onLoad={this.onMapLoad}
                >
                    <Search  />
                </WebScene>

                <div id="legendaFlexible">
                    {this.state.view &&
                        <Legend onLoad={this.onLegendLoad} widgetProperties={{ container: 'legendaFlexible' }} view={this.state.view} />
                    }
                </div>

                <div id="legenda" style={{ display: 'block', width: 200, marginTop: 50 }}>

                </div>
            </span>
        )
    }
}
```

**Comment by nicksenger** [comment]
@baierjak , the ArcGIS API for JavaScipt allows you to set a specific container element for the legend either during construction or after the widget has been instantiated.

You will need to use `esriPromise` to load the legend module from the API, then add it to your map with the desired container. Here's a link to the [ArcGIS JS API docs](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html#container) for this
