### ISSUE TITLE
Use of Widgets in v3

### ISSUE THREAD

**Issue by seanlarge** [nicksenger/react-arcgis#35]
Hi, I am on v 2.0.7 and am using the named widget component in my code. I'm using the search widget. Can you give an example of how to use the widget with version 3 of your api? thanks !

**Comment by nicksenger** [comment]
Hi @seanlarge,

The important thing to remember is that children of your `<Map />` or `<Scene />`, `<WebMap />`, `<WebScene />`  etc, have access to the map and view instances from the [ArcGIS JS API](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search.html) through their props. That said, here is an example of how you would make a basic search widget component:

```js
import * as React from 'react';
import { esriPromise } from 'react-arcgis';

export default class SearchWidget extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            widget: null
        };
    }

    render() {
        return null;
    }

    componentWillMount() {
        esriPromise([ 'esri/widgets/Search' ]).then(([ Search ]) => {
            const searchWidget = new Search({
                view: this.props.view
            });

            view.ui.add(searchWidget, {
                position: "top-left",
                index: 2
            });

            this.setState({ widget: searchWidget });
        }).catch((err) => console.error(err));
    }

    componentWillUnmount() {
        this.props.view.ui.remove(this.state.widget);
    }
}
```

You can see that the majority of this code is copied straight from the JS API documentation. React-arcgis is just a wrapper that gets the arcgis js api into your react application. Once your app is integrated with Esri's API, I think it is best to use the API directly and have the wrapper (react-arcgis) be as transparent as possible. This will allow you to get the most out of both react and the arcgis js api.

Hope this helps, and let me know if you have any further questions

**Comment by seanlarge** [comment]
ok cool, thank you. I'll work through this and let you know if I have questions

**Comment by nicksenger** [comment]
@seanlarge

Going to close this for now. Were you able to get this working?

**Comment by seanlarge** [comment]
@nicksenger this should do it, thanks
