### ISSUE TITLE
Search Widget events not working.

### ISSUE THREAD

**Issue by rupeshpawar** [nicksenger/react-arcgis#4]
Hi,

I am trying to add events for search widgets.

<SearchWidget position="top-left" onSearch-complete={this.handleSearch}/>

"onLoad" events work for me but anything else does not work.

I am looking for events here. https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search.html#events-summary

Please let me know.

**Comment by nicksenger** [comment]
@rupeshpawar 

Hi, thanks for checking out react-arcgis! 

Currently only the map components (`<Map />`, `<Scene />`, `<WebMap />` and `<WebScene />`) have been written to register handlers automatically using the react-style syntax. However, you can accomplish the same thing using `onLoad` to get a reference to the widget instance and adding the event handlers manually.

For example:

```js
render() {
  return (
    <Map className="my-map-class">
      <Search position="top-right" onLoad={this.registerSearchHandlers} />
    </Map>
  )
}

registerSearchHandlers(widgetInstance) {
  widgetInstance.on("search-complete", myCustomCallback);
}
```

I'll consider adding the react-style handlers (ie. props called `onSearchComplete` etc) to the widget components in the library if this is a common use-case.
