### ISSUE TITLE
move to Esri org?

### ISSUE THREAD

**Issue by jgravois** [nicksenger/react-arcgis#43]
hey @nicksenger! have you given any thought to moving this very popular project to [Esri's](https://github.com/Esri) GitHub organization?

if so: https://github.com/Esri/contributing/issues/18

happy to chat about it more if it'd be helpful to discuss the pros and cons.

**Comment by nicksenger** [comment]
Hey @jgravois! I hadn't though about it yet, but would be interested in talking about it some more.

This project has no CI step currently, though I could set something up if that's a requirement.

**Comment by jgravois** [comment]
maybe in 🌴 springs?

**Comment by nicksenger** [comment]
sounds good!
