### ISSUE TITLE
Failing to get most basic example working

### ISSUE THREAD

**Issue by alukach** [nicksenger/react-arcgis#51]
Hi, I write with a very vague issue:  I'm unable to get any example from the `README.md` to work.  I feel like I may very well be missing something basic or obvious but can't figure out what that would be.

I'm using `create-react-app` with the [`react-scripts-ts` scripts](https://github.com/wmonk/create-react-app-typescript) (i.e. `create-react-app myApp --scripts-version-react-scripts-ts`), as described in the [Microsoft Typescript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter) .

The `Map` component renders as "Loading.." and never proceeds further.  Neither the `onLoad` or `onError` handlers seem to be called.

You can find an example of the application here: https://codesandbox.io/s/170ooj28l

**Comment by alukach** [comment]
It seems that the `WebMap` example works: https://codesandbox.io/s/n5qnpzwk5l . Is the initial code example in the README supposed to serve purely as a demonstration and not as functional code?

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Map } from 'react-arcgis';

ReactDOM.render(
  <Map />,
  document.getElementById('container')
);
```

I admit that I'm not super familiar with the ArcGIS JS API, maybe I'm missing something fundamental there.

**Comment by nicksenger** [comment]
@alukach the issue with your app is that you did not give the container component any dimensions. The map does not have any inherent size -- it just expands to fill its containing element.

Changing the containing element in your app to, for example:
```html
<div id="root" style="width: 400px; height: 400px;"></div>
```
in `public/index.html` works fine. The example assumes that 'container' already has some dimensions.

**Comment by alukach** [comment]
Ah, of course, thanks.
