### ISSUE TITLE
Unable to change portalHostname for WebMap

### ISSUE THREAD

**Issue by DanielConlin** [nicksenger/react-arcgis#53]
Hello, I just recently started using the package, and everything works great as intended for my use case except the ability to change the portalHostaname for a WebMap. Our organization uses an internal maps server, and I am wondering if there is a plan for the WebMap to overwrite the arcgis online hostname. For example:
`<WebMap portalHostname="https://<portal location>/portal/sharing/rest/content/items" id="6627e1dd5f594160ac60f9dfc411673f" />`

**Comment by nicksenger** [comment]
Hi @DanielConlin,

You can achieve this by updating the `portalUrl` property of `esri/config` as described here: https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#portalUrl

You would need to make sure that `portalUrl` has been updated _before_ the webmap component renders. For example:

```js
import { WebMap, esriPromise } from 'react-arcgis';

export default class App {
  constructor(props) {
    this.state = { setPortal: false }
  }

  render() {
    if (this.state.setPortal) {
      return <WebMap id="abc123" />;
    }
    return null;
  }

  componentWillMount() {
    esriPromise(['esri/config']).then((esriConfig) => {
      esriConfig.portalUrl = 'https://myHostName.esri.com/arcgis';
      this.setState({  setPortal: true  });
    })
  }
}
```

Currently if you want to render webmaps from _both_ arcgis online and your own portal using the `WebMap` component from react-arcgis you would have to toggle this property back and forth. I'll look into providing better support for that in 3.3.0

**Comment by DanielConlin** [comment]
Hey @nicksenger,

Thanks for the reply, this helped solve the issue of not being able to change that value! Still working to solve some internal connectivity issues to the portal, but I don't think it is anything to do with the module, so I am marking this as closed. I appreciate your help.

Daniel
