### ISSUE TITLE
Error: [esri.core.Promise] DEPRECATED

### ISSUE THREAD

**Issue by leandroluk** [nicksenger/react-arcgis#56]
First of all, excuse my English, I had a help from the Google Translator ... =]

I'm starting to use your library and congratulations, it's very intuitive and functional, but in the most current version (3.3.0) when events occur in zoom in or zoom out a warning related to a promise is triggered:

![capturar](https://user-images.githubusercontent.com/8602982/41500944-8e501896-7171-11e8-9eb6-2bf9d93c38cf.PNG)

I think I would have to make the changes in the library, right?

**Comment by nicksenger** [comment]
@leandroluk You can hide these messages like this:

```ts
                <WebMap
                    loaderOptions={{
                        dojoConfig: {
                            has: {
                                'esri-promise-compatibility-deprecation-warnings': 0
                            }
                        }
                    }}
                />
```

I used the `<WebMap />` component as an example here but this will work with `<Map />`, `<Scene />` or `<WebScene />` components as well.

Closing as this isn't an issue with react-arcgis.
