### ISSUE TITLE
Using the "Map" component renders strangely.

### ISSUE THREAD

**Issue by aqouta** [nicksenger/react-arcgis#57]
Code such as:

`ReactDOM.render(<Map style={{ width: '20vw', height: '20vh' }}/>, document.getElementById('root'));`

creates a map of the appropriate size however the actual component appears to be 40vh in height and is split in half with the top half being the map and the bottom half containing any graphics placed within the map component. EX:
`ReactDOM.render(<Map style={{ width: '20vw', height: '20vh' }}><MapGraphic/></Map>, document.getElementById('root'));`

where MapGraphic is an exact copy of the 'BermudaTriangle ' code renders as 
 https://imgur.com/5b8u8gd

Replacing Map with Scene works as one would expect, only the Map component seems effected.

**Comment by nicksenger** [comment]
@aqouta that's odd. I'll try to repro this and get back to you.

**Comment by aqouta** [comment]
@nicksenger 

Thank you!

**Comment by nicksenger** [comment]
@aqouta the issue here is that you did not load esri's stylesheet: https://js.arcgis.com/4.8/esri/css/main.css
