### ISSUE TITLE
ElevationLayer Loading Error

### ISSUE THREAD

**Issue by okiwill** [nicksenger/react-arcgis#6]
Hi, thank you so much for your excellent working, I'm using this in our project now and it helps me a lot~~ 

According to the official SDK, the ElevationLayer should be added like this:
`map.ground.layers.add(elevLyr);`
If using `map.layers.add()`, ArcGIS API will just ignore the elevation layer and print some error message in the console.

I solved this by adding some if clause in the `LayerBase.tsx`, maybe you could fix this in future.

**Comment by nicksenger** [comment]
Hi okiwill, I'm glad that the library is helping with your project!

Thanks for letting me know about this issue. This is definitely a bug in the library, which assumes all layers are added to the map in the same way.

I'll add a fix for this and have it out shortly.

**Comment by nicksenger** [comment]
@okiwill 

I updated react-arcgis (v 1.1.3) so that it supports the alternate layer types like elevation layer. You can also now add a `layerview-create` or `layerview-destroy` callback using `onLayerviewCreate` or `onLayerviewDestroy` in the JSX.

Here's an example render function:

```js
    public render() {
        return (
            <Scene
                style={{ width: '100vw', height: '100vh' }}
                mapProperties={{ basemap: 'topo', ground: 'world-elevation' }}
                viewProperties={{
                    camera: {
                        heading: 300,
                        position: [-121.83, 48.279, 1346],
                        tilt: 60
                    }
                }}
            >
                <Layers.ElevationLayer
                    onLayerviewCreate={() => console.log('Created the elevation layer.')}
                    layerProperties={{
                        url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/OsoLandslide/OsoLandslide_After_3DTerrain/ImageServer'
                    }}
                />
            </Scene>
        );
    }
```

**Comment by okiwill** [comment]
I have updated my dependence to the newest version. It works fine now~ Thank you!
