### ISSUE TITLE
Popup Template not working properly

### ISSUE THREAD

**Issue by lauritapear** [nicksenger/react-arcgis#60]
I am having some issues with the popup template not working properly. It somehow works, since it is able to select my marker once clicked, however the popup template doesn't show. Here is a picture of how it looks when the marker is clicked https://github.com/lauritapear/ReactJS/blob/master/noPopup.png and below is my code. 

```
import * as React from 'react';

import { Map } from 'react-arcgis';

import { Scene } from 'react-arcgis';

import EsriMarker from '../EsriMarker';



class EsriMap extends React.Component{

    render() {

        return (

        <Scene style={{ width: '100vw', height: '100vh' }}

          mapProperties={{ basemap: 'streets-navigation-vector' }}

          viewProperties={{

              center: [172.58804957425, -43.5106019527023],

              zoom: 25

          }}>



           <EsriMarker  {...this.props}/>



        </Scene>

     );

    }

}



export default EsriMap;
```

```
import React from 'react';
import {loadModules} from 'react-arcgis';

class EsriMarker extends React.Component {
  render() {
    return null;
  }

  componentWillMount() {
    this.renderMarker();
  }

  renderMarker() {

    loadModules(["esri/layers/GraphicsLayer", "esri/Graphic",
    "esri/geometry/Point", "esri/PopupTemplate"])
    .then(([GraphicsLayer, Graphic, Point, PopupTemplate]) => {

      let markerLayer = new GraphicsLayer();
      this.props.markers.forEach(marker => {

        let point = new Point({
          x: parseFloat(marker.position.lng),
          y: parseFloat(marker.position.lat)
        });

        let markerSymbol = {
          type: "picture-marker",
          height: 25,
          width: 25,
          url: "../../images/blue.png"
        };

        let theAtt = {
          Name: "some name",
          Owner: "some Owner",
          Length: "some lengthß"
        };

        let pop = new PopupTemplate({
          title: "pop title",
          content: '<div className="info">ID: someID ' + '<br/><span>ZONE: someZone </span>'
        });

        const graphic = new Graphic({
          geometry: point,
          symbol: markerSymbol,
          attributes: theAtt,
          popupTemplate: pop
        });

        markerLayer.add(graphic);
      });

      this.props.view.map.add(markerLayer);
    }).catch((err) => console.error(err));
  }
}

export default EsriMarker;
```

**Comment by lauritapear** [comment]
@nicksenger Really?? that is weird, not sure why I am not getting the popup then :confused: I will double check my local settings. also I was trying to find information about this issue yesterday and found that arcgis 4.8 is having some issues with popups https://community.esri.com/thread/218033-esri-js-breaking-change-to-popuptemplate

Thanks for looking into this and for sharing your awesome library 👍

**Comment by nicksenger** [comment]
@lauritapear just to make sure, did you include the stylesheet for the js api in your html?

`<link rel="stylesheet" href="https://js.arcgis.com/4.8/esri/css/main.css">`

Not having that would definitely cause the popups to appear incorrectly.

**Comment by lauritapear** [comment]
@nicksenger I do have the stylesheet. I am thinking it may have something to do with the fact that my application is a plugin so the html is really on the other application my app runs on. Perhaps something on the bundle? I am assuming you run it on as standalone, right?

**Comment by nicksenger** [comment]
np! closing this as I don't think there is an issue with react-arcgis here
