### ISSUE TITLE
The zoom property of Scene does't work.

### ISSUE THREAD

**Issue by cabinhero** [nicksenger/react-arcgis#63]
what's wrong with my code?
  render() {
    return (
     <div style={{ width: '100vw', height: '100vh' }}>
       <Scene class="full-screen-map"
                  mapProperties={{ basemap: 'satellite' }}
                  viewProperties={{
                    center: [-64.78, 32.3],
                    zoom: 3
                  }}
       >
         <BermudaTriangle />
       </Scene>
    </div>
      )

  }

**Comment by nicksenger** [comment]
Fixed @ 3.3.3. Prior versions you will have to use the `scale` prop on scenes.
