### ISSUE TITLE
On build: 'error TS2304: Cannot find name 'Set'.'

### ISSUE THREAD

**Issue by Talamantez** [nicksenger/react-arcgis#64]
I ran into this error when running 'yarn build.'  Adding  "es6" to the "lib" section of tsconfig.js after pulling up this solution to the error on stackoverflow: https://stackoverflow.com/questions/39416691/webpack-ts2304-cannot-find-name-map-set-promise

 "lib": [
            "dom",
            "es5",
	    "es6",                      <-----  Added this
            "es2015.promise"
        ]

**Comment by nicksenger** [comment]
That's odd. I haven't seen any issues building with this as a dependency, though I also don't use yarn. Feel free to open a PR if you think this could help others.
